gsap.from(".navbar", {opacity:0, duration:2, delay:1, easy:"bounce", stagger:.6})
gsap.from(".container", {x:400, duration:2, delay:3, easy:"bounce"})
gsap.from(".one", {opacity:0, duration:2, delay:5, stagger:.6})
gsap.from(".two", {opacity:0, duration:2, delay:7, stagger:.6})
gsap.from(".three", {opacity:0, duration:2, delay:9, stagger:.6})
gsap.from(".foto1", {opacity:0, x:-400, duration:3, delay:5})
gsap.from(".foto2", {opacity:0, x:400, duration:3, delay:7})
gsap.from(".foto3", {opacity:0, x:-400, duration:3, delay:9})